config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'robots#index'
  get '/robots/search', to: 'robots#search'
  resources :robots
  resources :abilities, only: [:index, :show]

end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :robots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robot.rb
class Robot < ApplicationRecord
  has_one :ability
  validates :name, presence: true, uniqueness: true
  #validates :ability, presence: true
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController

  def index
    @abilities = Ability.all
  end

  def show
    @ability = Ability.find(params[:id])
    @robots = Robot.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  def index
    @robots = Robot.all
  end

  def new
    @robot = Robot.new
  end

  def create
    @robot = Robot.new(allowed_params)
    if @robot.valid?
      x = allowed_params[:name].split(" ")
      y = x.join
      @robot.image_url = "https://robohash.org/#{y}"
      @robot.save
      redirect_to robots_path
    else
      render :new
    end
  end

  def search
    query = params[:q]
    @robots = []
    robots = Robot.all.each do |x|
      if x.name.downcase.include?(query.downcase)
        @robots << x
      end
    end
    @robots
  end

  def show
    @robot = Robot.find(params[:id])
    @abilities = Ability.all
  end

  def edit
    @robot = Robot.find(params[:id])
    @abilities = Ability.all
  end

  def update
    @robot = Robot.find(params[:id])
    @robot.assign_attributes(allowed_params)
    if @robot.valid?
      x = allowed_params[:name].split(" ")
      y = x.join
      @robot.image_url = "https://robohash.org/#{y}"
      @robot.update(allowed_params)
      redirect_to robot_path
    else
      render :edit
    end
  end

  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy
    redirect_to robots_path
  end

private

def allowed_params
  params.require(:robot).permit(:name, :ability_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abilities/index.html.erb
<h1>All Abilities</h1>

<ul>
  <% @abilities.each do |ability| %>
    <li>
      <%= link_to ability.name, ability_path(ability.id) %>
      <br>
      Description: <%= ability.description %>
    </li>
    <br>
  <% end %>
</ul>

app/views/abilities/show.html.erb
<h1>About this Ability</h1>
<p>Ability Name:</p>
<li> <%= @ability.name %> </li>
<p>Ability Description:</p>
<li>  <%= @ability.description %> </li>
<p>Robots With This Ability:</p>
<% arr = []  %>
<% @robots.each do |robot| %>

  <% if robot.ability_id == @ability.id %>
      <% arr << robot %>
    <% end %>
  <% end %>
<% arr.each do |robot| %>
<li><%=link_to robot.name, robot_path(robot.id) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bots</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= link_to "Robots", robots_path %> // 
    <%= link_to "Abilities", abilities_path %> //
    <%= link_to "New Robot", new_robot_path %><br>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/edit.html.erb
<% if @robot.errors.any?  %>
      <ul>
        <% @robot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

<%= form_for @robot do |f| %>
      <p><%= f.label :name %></p>
      <%= f.text_field :name %><br/><br>
      <p><%= f.label :ability %></p>
      <%= f.collection_select :ability_id, Ability.all, :id, :name, prompt:true %>
      <br/><br>
    <%= f.submit %><br>
  <% end %>

app/views/robots/index.html.erb
<h1> All Robots</h1>

<%= form_tag("/robots/search", method: "get") do %>
  <p><%= label_tag(:q, "Search Robots by Name:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %></p>
<% end %>


<ul>
  <% @robots.each do |robot| %>
    <li>
      <%= link_to robot.name, robot_path(robot.id) %>
    </li>
    <br>
  <% end %>
</ul>

app/views/robots/new.html.erb
<h1>Create a Robot</h1>

<% if @robot.errors.any?  %>
      <ul>
        <% @robot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

<%= form_for :robot, url:robots_path do |f| %>
      <p><%= f.label :name %></p>
      <%= f.text_field :name %><br/><br>
      <p><%= f.label :ability %></p>
      <%= f.collection_select :ability_id, Ability.all, :id, :name, prompt:true %>
      <br/><br>
    <%= f.submit %><br>
  <% end %>

app/views/robots/search.html.erb
<h1> Robots that Match Your Search</h1>
<% @robots.each do |robot| %>
<li>Robot Name: <%=link_to robot.name, robot_path(robot.id) %></li>
<% end %>

app/views/robots/show.html.erb
<br>
<p>Robot Name:</p> <h1><%= @robot.name %></h1><br>
<img src= <%= @robot.image_url %>/><br>
<% @abilities.find do |ability| %>
<% if ability.id == @robot.ability_id %><br>
<p>Robot Ability:</p> <h2><%=link_to ability.name, ability_path(ability.id) %></h2>
<br><br>
<% end %>
<% end %>
<%= link_to "Edit", edit_robot_path %> //
<%= link_to "Destroy", robot_path(@robot.id), method: "DELETE" %>